language: python
python:
- 2.7
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- nosetests
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: qtgzNWmNyk6G9pyXsWqKktcnN7TeEBhHi8J99qa3pEFT2FTImkUaHDMObQQ6b8aQ6LWqBzH7ARFPlpIIPdALjQU/04ADCudRHo88Ycb+i0nRE7Gog17y5Y5/PceWJi9wY/2OL1Hv2AQZNKcptLDZak4H/TuFEW9mNVdx0ZFau7feA0y8vNbzVvSBzSazEfpbN8veQN5zfS6xotOJce19VjOWtV2F1Ln7Y/BD1BFw2wjBIg1Hx7O2prxI4pyoemhGyj0i5xKbLsD+mb0YHJU+Lu9EX66x9/oXsSIW/qcDjkj+ZJ16RvjfZGNwmKC/WMvx7g/tJL3eqvtHg7ogjGTMyNmPDMknjTrxm4QDgc6+tOYV68vKxc7uclQ7mq36PPIKlwB2OQo1vEgAlmJdcteyYCcCCkpDSrtLmXunkE+R5jzzoDQDEdR+UHih0QO1bPSC1F64pU6apwgnLmc+9uEaoQz63CzCqbRvULC5TWfxV9hyRbdFFLOeqvYMcm+0WLUKHu9yyx34+tFX5e883G5QB/9FIY1jZ3a5LwtgRZ+kimlfIEUt/9OJmBC4D+aBV8NU08ldbxrFdKwLV5p32lkzPJaDEeaXf9P/sBmFhkAubgVdWIomWhAJnBjvqClAYveKIx1v0EYdCnjNQl1xPzjjFujPb6N7aosO1YfnkUubT90=

  app: imagebuck
